name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to add...
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: What problem does this solve?
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues for duplicates.
        - label: I am willing to work on this feature myself.
